######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 14 00:38:32 2009
######################################################################
CONFIG-=app_bundle

MAKEFILE = QMakefile
TEMPLATE = app
TARGET = dist/gui
DEPENDPATH += . src ui 
INCLUDEPATH += . ./include ../fuzzy-lite/include
MOC_DIR = ./tmp/moc
OBJECTS_DIR = ./tmp
UI_HEADERS_DIR = include
UI_SOURCES_DIR = ui
RESOURCES += ui/resources.qrc
RCC_DIR = src/

DEFINES *= FL_USE_LOG FL_USE_DEBUG FL_USE_INLINE 

LIBS += -Ldist/ -lfuzzylite

#################### FORMS
FORMS += MainWindow.ui LinguisticVariable.ui LinguisticVariableWizard.ui
FORMS += DiscreteTerm.ui Grapher.ui Preferences.ui

#################### GUI
HEADERS += include/GuiLinguisticVariable.h include/GuiDiscreteTerm.h
SOURCES += src/GuiLinguisticVariable.cpp src/GuiDiscreteTerm.cpp

HEADERS += include/GuiLVarWizard.h include/GuiGrapher.h include/GuiPreferences.h
SOURCES += src/GuiLVarWizard.cpp src/GuiGrapher.cpp src/GuiPreferences.cpp

HEADERS += include/GuiMainWindow.h
SOURCES += src/GuiMainWindow.cpp


##################### HEADERS AND SOURCES
HEADERS += include/InputController.h include/OutputController.h include/RuleController.h
SOURCES += src/InputController.cpp src/OutputController.cpp src/RuleController.cpp

HEADERS += include/TestController.h
SOURCES += src/TestController.cpp

HEADERS += include/MainWindowController.h
SOURCES += src/MainWindowController.cpp



HEADERS += include/LinguisticVariableController.h
SOURCES += src/LinguisticVariableController.cpp

HEADERS += include/DiscreteTermController.h
SOURCES += src/DiscreteTermController.cpp

SOURCES += src/main.cpp
