fuzzylite: fl Namespace Reference
fl Namespace Reference
Template implementation.
Classes
class Accumulated
The Accumulated class is a special Term that stores a fuzzy set with the Activated terms from the Antecedents of a Rule, thereby serving mainly as the fuzzy output value of the OutputVariables.
class Activated
The Activated class is a special Term that contains pointers to the necessary information of a term that has been activated as part of the Antecedent of a Rule.
class Activation
The Activation class is the abstract class for RuleBlock activation methods.
class ActivationFactory
The ActivationFactory class is a ConstructionFactory of Activation methods for RuleBlocks.
class AlgebraicProduct
The AlgebraicProduct class is a TNorm that computes the algebraic product of any two values.
class AlgebraicSum
The AlgebraicSum class is an SNorm that computes the algebraic sum of values any two values.
class Antecedent
The Antecedent class is an expression tree that represents and evaluates the antecedent of a Rule.
class Any
The Any class is a special Hedge that always returns 1.0.
class Bell
The Bell class is an extended Term that represents the generalized bell curve membership function.
class Binary
The Binary class is an edge Term that represents the binary membership function.
class Bisector
The Bisector class is an IntegralDefuzzifier that computes the bisector of a fuzzy set represented in a Term.
class BoundedDifference
The BoundedDifference class is a TNorm that computes the bounded difference between any two values.
class BoundedSum
The BoundedSum class is an SNorm that computes the bounded sum of any two values.
class Centroid
The Centroid class is an IntegralDefuzzifier that computes the centroid of a fuzzy set represented in a Term.
class CloningFactory
The CloningFactory< T > class is the base class for a factory whose objects are created from a registered object by calling the clone() method.
class Concave
The Concave class is an edge Term that represents the concave membership function.
class Consequent
The Consequent class is a proposition set that represents and evaluates the consequent of a Rule.
class Console
The Console class is a command-line tool that helps to utilize the fuzzylite library.
class Constant
The Constant class is a (zero) polynomial Term that represents a constant value \(f(x) = k \).
class ConstructionFactory
The ConstructionFactory< T > class is the base class for a factory whose objects are created from a registered ConstructionFactory::Constructor.
class Cosine
The Cosine class is an extended Term that represents the cosine membership function.
class CppExporter
The CppExporter class is an Exporter that translates an Engine and its components to the C++ programming language using the fuzzylite library.
class Defuzzifier
The Defuzzifier class is the abstract class for defuzzifiers.
class DefuzzifierFactory
The DefuzzifierFactory class is a ConstructionFactory of Defuzzifiers.
class Discrete
The Discrete class is a basic Term that represents a discrete membership function.
class DrasticProduct
The DrasticProduct class is a TNorm that computes the drastic product of any two values.
class DrasticSum
The DrasticSum class is an SNorm that computes the drastic sum of any two values.
class EinsteinProduct
The EinsteinProduct class is a TNorm that computes the einstein product of any two values.
class EinsteinSum
The EinsteinSum class is an SNorm that computes the einstein sum of any two values.
class Engine
The Engine class is the core class of the library as it groups the necessary components of a fuzzy logic controller.
class Exception
The Exception class is the only type of exception that is utilized throughout the library.
class Exporter
The Exporter class is the abstract class for exporters to translate an Engine into different formats.
class Expression
The Expression class is the base class to build an expression tree.
class Extremely
The Extremely class is a Hedge located fifth in the ordered set (Not, Seldom, Somewhat, Very, Extremely, Any).
class FactoryManager
The FactoryManager class is a central class grouping different factories of objects, together with a singleton instance to access each of the factories throughout the library.
class FclExporter
The FclExporter class is an Exporter that translates an Engine and its components to the Fuzzy Control Language specification.
class FclImporter
The FclImporter class is an Importer that configures an Engine and its components utilizing the Fuzzy Control Language specification.
class First
The First class is a RuleBlock Activation method that activates the first rule whose activation degree is greater than the given threshold, and deactivates the remaining rules.
class FisExporter
The FisExporter class is an Exporter that translates an Engine and its components into the Fuzzy Inference System format for Matlab or Octave.
class FisImporter
The FisImporter class is an Importer that configures an Engine and its components from utilizing the Fuzzy Inference System format for Matlab or Octave.
class FldExporter
The FldExporter class is an Exporter that evaluates an Engine and exports its input values and output values to the FuzzyLite Dataset (FLD) format, see http://www.fuzzylite.com/fll-fld for more information.
class FllExporter
The FllExporter class is an Exporter that translates an Engine and its components to the FuzzyLite Language (FLL), see http://www.fuzzylite.com/fll-fld for more information.
class FllImporter
The FllImporter class is an Importer that configures an Engine and its components utilizing the FuzzyLite Language (FLL), see http://www.fuzzylite.com/fll-fld for more information.
class Function
The Function class is a polynomial Term that represents a generic function \(f : x \mapsto f(x) \).
class FunctionFactory
The FunctionFactory class is a CloningFactory of operators and functions utilized by the Function term.
class fuzzylite
The fuzzylite class contains global settings and information about the library.
class Gaussian
The Gaussian class is an extended Term that represents the Gaussian curve membership function.
class GaussianProduct
The GaussianProduct class is an extended Term that represents the two-sided Gaussian membership function.
class General
The General class is a RuleBlock Activation method that activates every rule following the order in which the rules were added to the rule block.
class HamacherProduct
The HamacherProduct class is a TNorm that computes the hamacher product of any two values.
class HamacherSum
The HamacherSum class is an SNorm that computes the hamacher sum of any two values.
class Hedge
The Hedge class is the abstract class for hedges.
class HedgeFactory
The HedgeFactory class is a ConstructionFactory of Hedges.
class Highest
The Highest class is a RuleBlock Activation method that activates a given number of rules with highest activation degrees in descending order.
class Importer
The Importer class is the abstract class for importers to configure an Engine and its components from different text formats.
class InputVariable
The InputVariable class is a Variable that represents an input of the fuzzy logic controller.
class IntegralDefuzzifier
The IntegralDefuzzifier class is the base class for defuzzifiers which integrate over the fuzzy set.
class JavaExporter
The JavaExporter class is an Exporter that translates an Engine and its components to the Java programming language using the jfuzzylite library.
class LargestOfMaximum
The LargestOfMaximum class is an IntegralDefuzzifier that computes the largest value of the maximum membership function of a fuzzy set represented in a Term.
class Last
The Last class is a RuleBlock Activation method that activates the last rule whose activation degree is greater than the given threshold, and deactivates the remaining rules.
class Linear
The Linear class is a linear polynomial Term expressed as \(f(x)= \mathbf{c}\mathbf{v}+k = \sum_i c_iv_i + k\), where variable \(x\) is not utilized, \(\mathbf{v}\) is a vector of values from the input variables, \(\mathbf{c}\) is a vector of coefficients, and \(k\) is a constant.
class Lowest
The Lowest class is a RuleBlock Activation method that activates a given number of rules with lowest activation degrees in ascending order.
class Maximum
The Maximum class is an SNorm that computes the maximum of any two values.
class MeanOfMaximum
The MeanOfMaximum class is an IntegralDefuzzifier that computes the mean value of the maximum membership function of a fuzzy set represented in a Term.
class Minimum
The Minimum class is a TNorm that computes the minimum of any two values.
class NilpotentMaximum
The NilpotentMaximum class is an SNorm that computes the nilpotent maximum of any two values.
class NilpotentMinimum
The NilpotentMinimum class is a TNorm that computes the nilpotent minimum of any two values.
class Norm
The Norm class is the abstract class for norms.
class NormalizedSum
The NormalizedSum class is an SNorm that computes the normalized sum of any two values.
class Not
The Not class is a Hedge located first in the ordered set (Not, Seldom, Somewhat, Very, Extremely, Any).
class Operation
The Operation class contains methods for numeric operations, string manipulation, and other functions, all of which are also accessible via fl::Op.
class Operator
The Operator class is an Expression that represents a non-terminal node in the expression tree as a binary operator (i.e., and or or) on two Expression nodes.
class OutputVariable
The OutputVariable class is a Variable that represents an output of the fuzzy logic controller.
class PiShape
The PiShape class is an extended Term that represents the Pi-shaped curve membership function.
class Proportional
The Proportional class is a RuleBlock Activation method that activates the rules utilizing activation degrees proportional to the activation degrees of the other rules, thus the sum of the activation degrees is equal to one.
class Proposition
The Proposition class is an Expression that represents a terminal node in the expression tree as variable is [hedge]* term.
class Ramp
The Ramp class is an edge Term that represents the ramp membership function.
class Rectangle
The Rectangle class is a basic Term that represents the rectangle membership function.
class Rule
The Rule class is a conditional statement that contributes to the control of an Engine.
class RuleBlock
The RuleBlock class contains a set of Rules and fuzzy logic operators required to control an Engine.
class Seldom
The Seldom class is a Hedge located second in the ordered set (Not, Seldom, Somewhat, Very, Extremely, Any).
class Sigmoid
The Sigmoid class is an edge Term that represents the sigmoid membership function.
class SigmoidDifference
The SigmoidDifference class is an extended Term that represents the difference between two sigmoidal membership functions.
class SigmoidProduct
The SigmoidProduct class is an extended Term that represents the product of two sigmoidal membership functions.
class SmallestOfMaximum
The SmallestOfMaximum class is an IntegralDefuzzifier that computes the smallest value of the maximum membership function of a fuzzy set represented in a Term.
class SNorm
The SNorm class is the base class for all S-Norms, and it is utilized as the disjunction fuzzy logic operator and as the aggregation (or accumulation in versions 5.0 and earlier) fuzzy logic operator.
class SNormFactory
The SNormFactory class is a ConstructionFactory of SNorms.
class Somewhat
The Somewhat class is a Hedge located third in the ordered set (Not, Seldom, Somewhat, Very, Extremely, Any).
class Spike
The Spike class is an extended Term that represents the spike membership function.
class SShape
The SShape class is an edge Term that represents the S-shaped membership function.
class Term
The Term class is the abstract class for linguistic terms.
class TermFactory
The TermFactory class is a ConstructionFactory of Terms.
class Threshold
The Threshold class is a RuleBlock Activation method that activates the rules whose activation degrees satisfy the equation given by the comparison operator and the threshold, and deactivates the rules which do not satisfy the equation.
class TNorm
The TNorm class is the base class for T-Norms, and it is utilized as the conjunction fuzzy logic operator and as the implication (or activation in versions 5.0 and earlier) fuzzy logic operator.
class TNormFactory
The TNormFactory class is a ConstructionFactory of TNorms.
class Trapezoid
The Trapezoid class is a basic Term that represents the trapezoidal membership function.
class Triangle
The Triangle class is a basic Term that represents the triangular membership function.
class Variable
The Variable class is an abstract class for linguistic variables.
class Very
The Very class is a Hedge located fourth in the ordered set (Not, Seldom, Somewhat, Very, Extremely, Any).
class WeightedAverage
The WeightedAverage class is a WeightedDefuzzifier that computes the weighted average of a fuzzy set represented in an Accumulated Term.
class WeightedDefuzzifier
The WeightedDefuzzifier class is the base class for defuzzifiers which compute a weighted function on the fuzzy set without requiring to integrate over the fuzzy set.
class WeightedSum
The WeightedSum class is a WeightedDefuzzifier that computes the weighted sum of a fuzzy set represented in an Accumulated Term.
class ZShape
The ZShape class is an edge Term that represents the Z-shaped membership function.
Typedefs
typedef double scalar
Represents floating-point values (typedef to float or double).
typedef Operation Op
A shortened type to refer to Operation.
Variables
const scalar nan = std::numeric_limits<scalar>::quiet_NaN()
Represents the Not-A-Number scalar value.
const scalar inf = std::numeric_limits<scalar>::infinity()
Represents the infinity scalar value.
const long null = 0L
Represents the C++11 or C++98 null pointer depending on whether the compilation flag -DFL_CPP11 is set.
Detailed Description
Template implementation.
The fl namespace is the namespace where all the classes of the fuzzylite library are contained in.
Todo:
utilize FL_BEGIN_NAMESPACE and FL_END_NAMESPACE
Author
Juan Rada-Vilela, Ph.D.
Since
4.0
Typedef Documentation
typedef Operation fl::Op
A shortened type to refer to Operation.
Definition at line 514 of file Operation.h.
typedef double fl::scalar
Represents floating-point values (typedef to float or double).
Represents floating-point values as doubles.
Definition at line 119 of file fuzzylite.h.
Variable Documentation
const scalar fl::inf = std::numeric_limits<scalar>::infinity()
Represents the infinity scalar value.
Definition at line 128 of file fuzzylite.h.
Referenced by fl::Operation::isInf(), and fl::Operation::toScalar().
const scalar fl::nan = std::numeric_limits<scalar>::quiet_NaN()
Represents the Not-A-Number scalar value.
Definition at line 124 of file fuzzylite.h.
Referenced by fl::Operation::mean(), and fl::Operation::toScalar().
const long fl::null = 0L
Represents the C++11 or C++98 null pointer depending on whether the compilation flag -DFL_CPP11 is set.
Definition at line 174 of file fuzzylite.h.
Referenced by fl::CloningFactory< T >::cloneObject(), fl::CloningFactory< T >::CloningFactory(), fl::ConstructionFactory< T >::constructObject(), fl::ConstructionFactory< T >::getConstructor(), fl::CloningFactory< T >::getObject(), and fl::CloningFactory< T >::operator=().