name: FuzzyLite (Windows)

on:
  pull_request:
    branches: [ "main" ]
  push: 
    branches: [ "main" ]
  schedule: 
    # run monthly on the first day
    - cron: "0 0 1 * * "

jobs:
  build:
    runs-on: windows-latest
    
    strategy: 
      fail-fast: false
      matrix:
        build_type: ["release", "debug"]
        use_cpp98: ["OFF", "ON"]
        use_float: ["OFF", "ON"]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Building FuzzyLite
      working-directory: fuzzylite
      shell: cmd
      env: 
        FL_CPP98: ${{ matrix.use_cpp98 }}
        FL_USE_FLOAT: ${{ matrix.use_float }}
        FL_BUILD_TESTS: "ON"
      run: |
        build.bat ${{ matrix.build_type }}