name: Linux Test Build

on:
  push:
    branches: [ "build/*" ]

jobs:
  build-clang:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [ "release" ]
        compiler_version: [ "13", "14", "15"]

    steps:
      - uses: actions/checkout@v4

      - name: Building FuzzyLite
        working-directory: fuzzylite
        env:
          CXX: clang++-${{ matrix.compiler_version }}
        run: |
          ${{env.CXX}} --version

  build-gcc:
    runs-on: ubuntu-22.04
  
    strategy:
      fail-fast: false
      matrix:
        build_type: [ "release" ]
        compiler_version: [ "9", "10", "11", "12", "13" ]
  
    steps:
    - uses: actions/checkout@v4
  
    - name: Building FuzzyLite
      working-directory: fuzzylite
      env:
        CXX: g++-${{ matrix.compiler_version }}
      run: |
        ${{env.CXX}} --version
  