name: Linux Test Build

on:
  push:
    branches: [ "build/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        build_type: [ "release" ]
        use_cxx: [ "clang++" ]

    steps:
      - uses: actions/checkout@v4

      - name: Building FuzzyLite
        working-directory: fuzzylite
        env:
          CXX: ${{ matrix.use_cxx }}
        run: |
          which clang++
          ls -la /
          ls -la /usr/bin
          ls -la /bin
          clang++ --version
