name: Build FuzzyLite C++

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main, '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy: 
      fail-fast: false
      matrix:
        use_cxx: ["clang++"]
        build_type: ["release", "debug"]
        use_cpp98: ["OFF"]
        use_float: ["OFF"]


    steps:
    - uses: actions/checkout@v2
    
    - name: Build FuzzyLite (Release)
      working-directory: fuzzylite
      env: 
        FL_CPP98: ${{ matrix.use_cpp98 }}
        FL_USE_FLOAT: ${{ matrix.use_float }}
        CXX: ${{ matrix.use_cxx }}
        FL_BUILD_TESTS: "ON"
      run: |
        bash build.sh release
    
    - name: Build FuzzyLite (Debug)
      working-directory: fuzzylite
      env: 
        FL_CPP98: ${{ matrix.use_cpp98 }}
        FL_USE_FLOAT: ${{ matrix.use_float }}
        CXX: ${{ matrix.use_cxx}}
        FL_BUILD_TESTS: "ON"
      run: |
        bash build.sh debug