name: Linux Full Build

on:
  push:
    branches: [ "build/*", "build-linux/*" ]

jobs:
  build-clang:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler_version: [ "13", "14", "15"]
        build_type: [ "release", "debug" ]
        use_cpp98: [ "OFF", "ON" ]
        use_float: [ "OFF", "ON" ]

    steps:
      - uses: actions/checkout@v4

      - name: Restore cmake dependencies
        id: cache-restore-cmake-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            build/_deps
          key: ${{ runner.os }}-cmake-deps

      - name: Building FuzzyLite
        env:
          CXX: clang++-${{ matrix.compiler_version }}
        run: |
          cmake -B build/ -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DFL_CPP98=${{ matrix.use_cpp98 }} -DFL_USE_FLOAT=${{ matrix.use_float }} .
          cmake --build build/ --parallel
          ctest --test-dir build/

  build-gcc:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler_version: [ "9", "10", "11", "12", "13" ]
        build_type: [ "release" ]
        use_cpp98: [ "OFF", "ON" ]
        use_float: [ "OFF", "ON" ]

    steps:
      - uses: actions/checkout@v4

      - name: Restore cmake dependencies
        id: cache-restore-cmake-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            build/_deps
          key: ${{ runner.os }}-cmake-deps

      - name: Building FuzzyLite
        env:
          CXX: g++-${{ matrix.compiler_version }}
        run: |
          cmake -B build/ -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DFL_CPP98=${{ matrix.use_cpp98 }} -DFL_USE_FLOAT=${{ matrix.use_float }} .
          cmake --build build/ --parallel
          ctest --test-dir build/
