name: Linux Build (monthly)

on:
  schedule: # monthly, first day
    - cron: 0 0 1 * *
  pull_request:
    branches: [ build/*, build-linux/* ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [ clang++-18, g++-14 ]
        cxx-standard: [ 98, 11, 14, 17, 20, 23 ]
        use_float: [ OFF, ON ]

    steps:
      - uses: actions/checkout@v4

      - name: Restore dependencies
        id: restore-dependencies
        uses: actions/cache/restore@v4
        with:
          path: .local/
          key: ${{ runner.os }}-local

      - name: Building fuzzylite
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          pip install --target .local/site-packages tools/dev
          nox -- strict=on cxx_standard=${{ matrix.cxx-standard }} use_float=${{ matrix.use_float }}

      - name: Save dependencies
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        id: save-dependencies
        uses: actions/cache/save@v4
        with:
          path: .local/
          key: ${{ steps.restore-dependencies.outputs.cache-primary-key }}