name: Linux Build (monthly)

on:
  schedule: # monthly, first day
    - cron: 0 0 1 * *
  pull_request:
    branches: [ build/*, build-linux/* ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cxx: [ clang++-18, g++-14 ]
        cxx-standard: [ 98, 11, 14, 17, 20, 23 ]
        use_float: [ OFF, ON ]

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: fuzzylite-cache
        uses: actions/cache@v3
        with:
          path: .local/
          key: ${{ runner.os }}-build-${{ hashFiles('tools/dev/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Building fuzzylite
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          make devtools && source `make venv_activate`
          nox -e install_catch2
          nox -- strict=on cxx_standard=${{ matrix.cxx-standard }} use_float=${{ matrix.use_float }}
