name: Windows Medium Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [ "release", "debug" ]
        platform: [ "x64", "win32" ]

    steps:
      - uses: actions/checkout@v4
      
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Restore cmake dependencies
        id: cache-restore-cmake-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            fuzzylite/build/${{ matrix.build_type }}/_deps
          key: ${{ runner.os }}-cmake-deps

      - name: Building FuzzyLite
        working-directory: fuzzylite
        shell: cmd
        run: |
          cmake -B build/${{ matrix.build_type }} -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .
          cmake --build build/${{ matrix.build_type }} --parallel
          ctest --test-dir build/${{ matrix.build_type }}
