name: FuzzyLite (Windows) [Push]

on:
  push:
    branches: [ "main", "build/**" ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy: 
      fail-fast: false
      matrix:
        build_type: ["release"]
        use_cpp98: ["OFF"]
        use_float: ["OFF"]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Building FuzzyLite
      working-directory: fuzzylite
      shell: cmd
      env: 
        FL_CPP98: ${{ matrix.use_cpp98 }}
        FL_USE_FLOAT: ${{ matrix.use_float }}
        FL_BUILD_TESTS: "ON"
      run: |
        build.bat ${{ matrix.build_type }}