name: FuzzyLite (Windows)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    name: Windows-VisualStudio-${{matrix.platform}}

    strategy:
      fail-fast: false
      matrix:
        platform: [ 'x64', 'win32' ]
        build_type: [ "release", "debug" ]
        use_cpp98: [ "OFF", "ON" ]
        use_float: [ "OFF", "ON" ]

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Building FuzzyLite
        working-directory: fuzzylite
        shell: cmd
        env:
          FL_CPP98: ${{ matrix.use_cpp98 }}
          FL_USE_FLOAT: ${{ matrix.use_float }}
          FL_BUILD_TESTS: "OFF"
        run: |
          cmake -B build/${{ matrix.build_type }} -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .
          cmake --build build/${{ matrix.build_type }} --parallel
